= Prototyping with Tool Calling

== Basic Tool Calling

Open up the following notebook in your workspace.

In this notebook we will introduce how to build a simple agent using Llama Stack's agent framework, enhanced with a single tool: the builtin web search tool.

We will cover the agent basics. This is an important step toward developing a more capable and autonomous agent.

== Prompt Chaining

Open up the following notebook in your workspace.

These approaches allow the agent to complete multi-step tasks, dynamically choose tools, and adjust its behavior based on context.

== ReAct

Open up the following notebook in your workspace.

= Prototyping with MCP

Open up the following notebook in your workspace.

This notebook is for developers who are already familiar with basic agent workflows. Here, we will highlight more advanced use cases for agents where a single tool call is insufficient to complete the required task.

We will also use https://github.com/modelcontextprotocol/servers[MCP tools] (which can be deployed onto an OpenShift cluster) throughout this demo to show users how to extend their agents beyond Llama Stacks's current builtin tools and connect to many different services and data sources to build their own custom agents.
