= Hitchhikers Guide to Secrets Management

Adding new secrets for **ai-agent** app.

. decrypt secrets
+
[source,bash,options="wrap",role="execute"]
----
cd ~/git/etx-agentic-ai
ansible-vault encrypt infra/secrets/vault-sno
ansible-vault decrypt infra/secrets/vault-sno
# key generated using - openssl rand -hex 32
456...
----

. add you secrets into a new app - naming convention is the same name as the folder in applications/ or tenants/
+
[source,bash,options="wrap",role="execute"]
----
# ai-agent
APP_NAME=ai-agent
if prompt_update ${APP_NAME}; then
  vault kv put kv/$TEAM_ENVIRONMENT/$CLUSTER_NAME/$PROJECT_NAME/$APP_NAME \
    MODEL_LLAMA3_API_KEY=${MODEL_LLAMA3_API_KEY} \
    MODEL_LLAMA4_API_KEY=${MODEL_LLAMA4_API_KEY} \
    MODEL_EMBED_API_KEY=${MODEL_EMBED_API_KEY} \
    TAVILY_SEARCH_API_KEY=${TAVILY_SEARCH_API_KEY}
fi
----

. hydrate the vault - add all of them - you will be prompted for ROOT_TOKEN
+
[source,bash,options="wrap",role="execute"]
----
export CLUSTER_NAME=sno
export BASE_DOMAIN=sandbox2010.opentlc.com
export VAULT_ROUTE=vault-vault.apps.${CLUSTER_NAME}.${BASE_DOMAIN}
export VAULT_ADDR=https://${VAULT_ROUTE}
export VAULT_SKIP_VERIFY=true
export ROOT_TOKEN=hvs...

vault login token=${ROOT_TOKEN}

sh infra/secrets/vault-sno
----

. encrypt the file + check it in - see 1 - use same key! also note: we have the pre-commit to stop infosec incidents like yesterday !!! 🔐
https://github.com/redhat-ai-services/etx-agentic-ai/blob/main/infra/bootstrap/pre-commit[pre-commit,window=_blank]
https://redhat-ai-services.github.io/etx-agentic-ai/modules/module-00.html#_the_secrets_file[secrets doc,window=_blank]

. update source code to add secrets e.g. heres is one example ! (you could have multiple secrets, or put this in **ANY YAML** not just a secrets file - this is the main benefit/ difference with ESO) - huge benefit when you consider that not all CRs do the right thing as far as secrets ref: goes.
+
[source,bash,options="wrap",role="execute"]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: my-ai-agent-secret
type: Opaque
stringData:
    MODEL_LLAMA3_API_KEY: <MODEL_LLAMA3_API_KEY>
    MODEL_LLAMA4_API_KEY: <MODEL_LLAMA4_API_KEY>
    MODEL_EMBED_API_KEY: <MODEL_EMBED_API_KEY>
    TAVILY_SEARCH_API_KEY: <TAVILY_SEARCH_API_KEY>
----

. we need to tell the top level THING (which is the PolicyGen) where to look in Vault - avp.kubernetes.io/path - hence the pattern of duplicating secrets in the secrets file for each app - then they can be managed indivdually if need to. also not kv/data path here - vault has virtual folder structure internally! if you search in the code base for avp.kubernetes.io - you will see different patterns of usage - https://argocd-vault-plugin.readthedocs.io/en/stable/[argocd vault plugin docs - a must read,window=_blank]
+
[source,yaml,options="wrap",role="execute"]
----
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous",
                      "avp.kubernetes.io/path": "kv/data/ocp/sno/openshift-policy/ai-agent"}
----

. heres the commit - https://github.com/redhat-ai-services/etx-agentic-ai/commit/171c1e5ecc049be82097c8b8112ea7bc30c2aec7

. you have not got an app-of-app for ai-agent yet => create one! make sure it uses the sidecar that hydrates secrets (as opposed to say argocd-novault-plugin-kustomize)
+
[source,yaml,options="wrap",role="execute"]
----
        plugin:
          name: argocd-vault-plugin-kustomize
----

. login to Argo CD -> check it all worked - hit hard refresh to resync from Vault (this is an argo thing). I have configured Argo CD to hard refresh hourly .. so whats in vault is REAL on cluster:
https://github.com/redhat-ai-services/etx-agentic-ai/blob/main/infra/bootstrap/setup-cr.yaml#L447-L448
