FROM registry.access.redhat.com/ubi9/python-311

USER root

RUN dnf -y update \
 && dnf -y install python3-pip \
 && dnf -y clean all \
 && rm -rf /var/cache/dnf \
 && pip install pip==24.2 setuptools==80.8.0

USER 1001

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
COPY *.py ./

CMD fastapi run main.py
