---
namespace: demo-pipeline
registry: image-registry.openshift-image-registry.svc:5000
application_name: undertow-servlet
git_url: https://github.com/nstrug/openshift-quickstarts.git
git_subdirectory: undertow-servlet
git_revision: good
git_revision_bad: bad
agent_endpoint: http://agent-service-test-2.agent-demo.svc.cluster.local:8000/report-failure

# Service Account configuration
serviceAccount:
  name: pipeline

# Role Binding configuration
roleBinding:
  name: openshift-pipelines-edit
  clusterRole: edit

# Job configuration
jobs:
  good:
    name: trigger-java-app-build-good
    enabled: true
  bad:
    name: trigger-java-app-build-bad
    enabled: true
    waitForGoodJob: true

# Pipeline configuration
pipeline:
  name: java-app-build
  timeout: 1h0m0s

# Workspace configuration
workspace:
  name: shared-workspace
  storage: 3Gi

# Container images
images:
  cliTool: registry.redhat.io/openshift4/ose-cli:latest

