# registry.redhat.io/ubi9/python-39:9.6-1754271155
FROM quay.io/modh/cuda-notebooks:3.9 as builder
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD dev-red-rag.tar.gz .
USER root
RUN mkdir /opt/app-root/src/.cache/huggingface && \
    chmod 777 /opt/app-root/src/.cache/huggingface
RUN mkdir -p /opt/app-root/src/.cache/torch_extensions && \
    chmod -R 777 /opt/app-root/src/.cache/torch_extensions
USER 1001

FROM builder
ENV TORCH_CUDA_ARCH_LIST=8.9
ENV INDEX_NAME=dev-red-rag
ENV INDEX_ROOT=/opt/app-root/src
ENV PORT=8081
EXPOSE 8081
ADD server.py server.py
ENTRYPOINT [ "python", "server.py" ]
