---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etx-ai-app-of-apps
  namespace: openshift-policy
  labels:
    rht-gitops.com/openshift-policy: policies
spec:
  destination:
    namespace: openshift-policy
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: infra/app-of-apps/sno
    directory:
      include: "*.yaml"
    repoURL: https://github.com/carlmes/etx-agentic-ai.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
