# Cluster Observability Operator configuration

# Namespace configuration
namespace:
  name: openshift-cluster-observability-operator
  create: true
  annotations:
    openshift.io/display-name: "Cluster Observability Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'

# Operator subscription configuration
subscription:
  # Name of the subscription
  name: cluster-observability-operator
  # Package name for the operator
  packageName: cluster-observability-operator
  # Channel to subscribe to (stable, fast, etc.)
  channel: stable
  # Source catalog containing the operator
  source: redhat-operators
  # Namespace where the catalog source is located
  sourceNamespace: openshift-marketplace
  # Installation plan approval mode
  installPlanApproval: Automatic
  # Starting CSV (leave empty for latest)
  startingCSV: "cluster-observability-operator.v1.2.0"

# OperatorGroup configuration
operatorGroup:
  # Name of the operator group
  name: openshift-cluster-observability-operator
  # Target namespaces (empty for all namespaces)
  targetNamespaces: []

# Global labels to apply to all resources
commonLabels: {}

# Global annotations to apply to all resources
commonAnnotations: {}

# Metadata labels configuration
metadataLabels:
  # Labels to apply to the subscription metadata
  subscription:
    operators.coreos.com/cluster-observability-operator.openshift-cluster-observability: ''

# Resource limits and requests (if needed for operator pod)
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Node selector for operator pod
nodeSelector: {}

# Tolerations for operator pod
tolerations: []

# Affinity for operator pod
affinity: {}